language: php

php:
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4
  - hhvm
  - nightly

matrix:
  include:
    - php: 5.3
      dist: precise
  fast_finish: true
  allow_failures:
    - php: nightly

dist: trusty
sudo: false
