language: php

dist: trusty
sudo: false

stages:
  - Code Style and Static Analysis
  - test
  - Test CommonMark (weak)

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly
  - hhvm
  - hhvm-nightly

matrix:    
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm-nightly
    - php: 7.3

install:
  - composer install --prefer-dist --no-interaction --no-progress

script:
  - composer test-units

cache:
  directories:
    - $HOME/.composer/cache

jobs:
  include:
    - stage: Code Style and Static Analysis
      php: 7.2
      script:
        - '[ -z "$TRAVIS_TAG" ] || [ "$TRAVIS_TAG" == "$(php -r "require(\"vendor/autoload.php\"); echo Erusev\Parsedown\Parsedown::version;")" ]'
        - composer test-formatting

    - stage: Test CommonMark (weak)
      php: 7.2
      script:
        - composer test-commonmark-weak || true
      allow_failures:
        - php: 7.2
